name: CI build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          java-version: '21'
          distribution: temurin
          cache: maven
      - uses: jbangdev/setup-jbang@cc28889678db839e29433f42f9ff25f148b6d8de # main
      - name: Verify
        run: ./mvnw --batch-mode --no-transfer-progress clean verify
      - name: Upload previews and test reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: verification-results
          path: |
            target/previews/
            target/surefire-reports/
            target/failsafe-reports/
